### ISSUE TITLE
error in examples

### ISSUE THREAD

**Issue by aspitaleri** [Lab41/squiggle#4]
Hi,
I have installed squiggle by pip3 but I got this error in running examples:
squiggle ecol.heg.fasta

Visualizing each sequence in black.
  0%|                                                                                                                 | 0/274 [00:00<?, ? seqs/s]BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
Traceback (most recent call last):
  File "/usr/local/bin/squiggle", line 11, in <module>
    load_entry_point('squiggle==0.3.1', 'console_scripts', 'squiggle')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/squiggle/cli.py", line 223, in visualize
    color=seq.color)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/plotting/_decorators.py", line 54, in wrapped
    return create_renderer(glyphclass, self, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/plotting/_renderer.py", line 126, in create_renderer
    update_legend(plot, legend_kwarg, glyph_renderer)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/plotting/_legends.py", line 56, in update_legend
    _LEGEND_KWARG_HANDLERS[kwarg](value, legend, glyph_renderer)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/plotting/_legends.py", line 82, in _handle_legend_deprecated
    raise ValueError("Bad 'legend' parameter value: %s" % label)
ValueError: Bad 'legend' parameter value: None

The only fasta that I can successfully run is
>lcl|NC_000011.10_cds_NP_000509.1_1 [gene=HBB]
ATGGTGCATCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAG
TTGGTGGTGAGGCCCTGGGCAGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAGTCCTTTGG
GGATCTGTCCACTCCTGATGCTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCAAGAAAGTGCTCGGT
GCCTTTAGTGATGGCCTGGCTCACCTGGACAACCTCAAGGGCACCTTTGCCACACTGAGTGAGCTGCACT
GTGACAAGCTGCACGTGGATCCTGAGAACTTCAGGCTCCTGGGCAACGTGCTGGTCTGTGTGCTGGCCCA
TCACTTTGGCAAAGAATTCACCCCACCAGTGCAGGCTGCCTATCAGAAAGTGGTGGCTGGTGTGGCTAAT
GCCCTGGCCCACAAGTATCACTAA
>lcl|NC_005100.4_cds_NP_150237.1_1 [gene=HBB]
ATGGTGCACCTGACTGATGCTGAGAAGGCTGCTGTTAATGGCCTGTGGGGAAAGGTGAACCCTGATGATG
TTGGTGGCGAGGCCCTGGGCAGGCTGCTGGTTGTCTACCCTTGGACCCAGAGGTACTTTGATAGCTTTGG
GGACCTGTCCTCTGCCTCTGCTATCATGGGTAACCCTAAGGTGAAGGCCCATGGCAAGAAGGTGATAAAC
GCCTTCAATGATGGCCTGAAACACTTGGACAACCTCAAGGGCACCTTTGCTCATCTGAGTGAACTCCACT
GTGACAAGCTGCATGTGGATCCTGAGAACTTCAGGCTCCTGGGCAACATGATTGTGATTGTGTTGGGCCA
CCACCTGGGCAAGGAATTCTCCCCCTGTGCACAGGCTGCCTTCCAGAAGGTGGTGGCTGGAGTGGCCAGT
GCCCTGGCTCACAAGTACCACTAA

**Comment by Benjamin-Lee** [comment]
Thanks for reporting this! I need update the code to work with the new version of Bokeh. In the mean time, feel free to use DNAvisualization.org, which should work since it doesn't use Bokeh.

**Comment by Benjamin-Lee** [comment]
Fixed it!
